export const ROLES = {
  ADMIN: "Admin",
  DOCTOR: "Doctor",
  RECEPTIONIST: "Receptionist",
  LAB_STAFF: "Lab Staff",
};

export const ROLE_ACCESS = {
  dashboard: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.RECEPTIONIST, ROLES.LAB_STAFF],
  doctorPanel: [ROLES.DOCTOR],
  patients: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.RECEPTIONIST],
  appointments: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.RECEPTIONIST],
  uploads: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.LAB_STAFF],
  aiSupport: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.LAB_STAFF, ROLES.RECEPTIONIST],
  billing: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.RECEPTIONIST],
  feeConfig: [ROLES.ADMIN],
  myFeeConfig: [ROLES.DOCTOR],
  analytics: [ROLES.ADMIN],
  opdManagement: [ROLES.ADMIN],   // NEW
  staffManagement: [ROLES.DOCTOR, ROLES.ADMIN],
};