import os
import tempfile
import traceback
import json
import base64
import fitz  # PyMuPDF
from flask import request, jsonify
from config.db import db
from google import genai
from google.genai import types

reports_collection = db["reports"]

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

MEDICAL_DISCLAIMER = (
    "⚠️ IMPORTANT DISCLAIMER: This analysis is generated by an AI system and is "
    "intended for informational purposes ONLY. It is NOT a medical diagnosis and should "
    "NEVER replace professional medical advice, examination, or treatment. Always consult "
    "a qualified and licensed healthcare professional before making any medical decisions. "
    "In case of a medical emergency, contact emergency services immediately."
)


def get_client():
    """Get a configured Gemini client."""
    if not GEMINI_API_KEY or GEMINI_API_KEY == "your_free_gemini_api_key_here":
        return None
    return genai.Client(api_key=GEMINI_API_KEY)


def extract_text_from_pdf(filepath: str) -> str:
    """Extract text from a PDF file using PyMuPDF."""
    try:
        doc = fitz.open(filepath)
        text = ""
        for page in doc:
            text += page.get_text()
        doc.close()
        return text.strip()
    except Exception as e:
        return f"[PDF extraction error: {e}]"


def extract_text_from_image(filepath: str, client) -> str:
    """Extract text from an image using Gemini Vision."""
    try:
        with open(filepath, "rb") as f:
            image_data = f.read()

        ext = os.path.splitext(filepath)[1].lower().strip(".")
        mime_map = {"jpg": "image/jpeg", "jpeg": "image/jpeg", "png": "image/png",
                    "tiff": "image/tiff", "tif": "image/tiff", "bmp": "image/bmp"}
        mime_type = mime_map.get(ext, "image/jpeg")

        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=[
                "Extract ALL text from this medical report image exactly as it appears, "
                "including all numbers, values, units, reference ranges, and labels. "
                "Do not interpret or summarize — just extract the raw text.",
                types.Part.from_bytes(data=image_data, mime_type=mime_type)
            ]
        )
        return response.text.strip()
    except Exception as e:
        return f"[Image text extraction error: {e}]"


def extract_text_from_file(filepath: str, client=None) -> str:
    """Smart text extraction based on file type."""
    ext = os.path.splitext(filepath)[1].lower()

    if ext == ".pdf":
        text = extract_text_from_pdf(filepath)
        # If PDF has very little text (possibly scanned), try vision
        if len(text) < 50 and client:
            return extract_text_from_image(filepath, client)
        return text

    elif ext in [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"]:
        if client:
            return extract_text_from_image(filepath, client)
        return "[Image analysis requires Gemini API key]"

    else:
        try:
            with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                return f.read().strip()
        except Exception as e:
            return f"[File read error: {e}]"


def build_analysis_prompt(report_text: str, user_question: str) -> str:
    """Build the structured medical analysis prompt."""
    return f"""You are an expert medical AI assistant analyzing a patient's medical report. 
Your analysis must be accurate, evidence-based, and cautious. 
Base your response ONLY on the information present in the report.

MEDICAL REPORT CONTENT:
---
{report_text[:10000]}
---

PATIENT QUESTION: {user_question}

Analyze this report and respond in the following JSON format ONLY (no other text):
{{
  "summary": "Clear 2-3 sentence summary of what this report shows and its overall significance",
  "possible_conditions": [
    {{
      "condition": "Name of potential condition/finding",
      "evidence": "Specific data from the report that suggests this",
      "confidence": "High/Medium/Low"
    }}
  ],
  "key_findings": [
    "Key finding 1 from the report with specific values",
    "Key finding 2 from the report with specific values"
  ],
  "normal_values": [
    "Value that is within normal range"
  ],
  "precautions": [
    "Specific precaution or recommendation",
    "Lifestyle change recommendation"
  ],
  "urgency_level": "Routine OR Soon OR Urgent OR Emergency",
  "urgency_reason": "Brief explanation for the urgency level",
  "when_to_seek_immediate_help": [
    "Specific symptom or situation requiring immediate medical attention"
  ],
  "questions_for_doctor": [
    "Important question patient should ask their doctor"
  ],
  "disclaimer": "This AI analysis is for informational purposes only and does not constitute medical advice. Always consult a qualified healthcare professional."
}}

CRITICAL RULES:
1. Only mention conditions that have clear evidence in the report
2. If values are normal, say so explicitly
3. If something cannot be determined from the report, state "Cannot be determined from available information"
4. Always prefer caution over optimism in urgency assessment
5. Return ONLY valid JSON — no markdown, no extra text"""


def call_gemini(client, prompt: str) -> dict:
    """Call Gemini and parse the JSON response."""
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.1,
            max_output_tokens=3000,
        )
    )

    raw = response.text.strip()

    # Remove markdown code fences if present
    if raw.startswith("```"):
        parts = raw.split("```")
        raw = parts[1] if len(parts) > 1 else raw
        if raw.startswith("json"):
            raw = raw[4:]

    raw = raw.strip().rstrip("```").strip()
    return json.loads(raw)


def analyze_report():
    """Analyze an existing report by report_id or filepath."""
    client = get_client()
    if not client:
        return jsonify({
            "success": False,
            "error": "Gemini API key not configured. Please:\n"
                     "1. Go to https://aistudio.google.com/app/apikey\n"
                     "2. Click 'Create API Key' (it's FREE)\n"
                     "3. Copy the key and add GEMINI_API_KEY=your_key to server/.env\n"
                     "4. Restart the server"
        }), 503

    try:
        data = request.json or {}
        report_id = data.get("report_id")
        user_question = data.get("question", "What does this medical report indicate? Are the values normal? What precautions should I take?")
        filepath = data.get("filepath")

        if report_id and not filepath:
            from bson import ObjectId
            report = reports_collection.find_one({"_id": ObjectId(report_id)})
            if not report:
                return jsonify({"success": False, "error": "Report not found"}), 404
            filepath = report.get("filepath")

        if not filepath or not os.path.exists(filepath):
            return jsonify({"success": False, "error": "Report file not found on server. It may have been moved or deleted."}), 404

        report_text = extract_text_from_file(filepath, client)

        if not report_text or len(report_text.strip()) < 20:
            return jsonify({
                "success": False,
                "error": "Could not extract meaningful text from this report. The file may be a scanned image or corrupted."
            }), 422

        prompt = build_analysis_prompt(report_text, user_question)
        analysis = call_gemini(client, prompt)

        return jsonify({
            "success": True,
            "analysis": analysis,
            "extracted_text_preview": report_text[:300] + "..." if len(report_text) > 300 else report_text
        }), 200

    except json.JSONDecodeError as e:
        return jsonify({"success": False, "error": f"AI response parsing error: {e}"}), 500
    except Exception as e:
        traceback.print_exc()
        return jsonify({"success": False, "error": f"Analysis failed: {str(e)}"}), 500


def analyze_uploaded_report():
    """Analyze a freshly uploaded report file."""
    client = get_client()
    if not client:
        return jsonify({
            "success": False,
            "error": "Gemini API key not configured. Get your FREE key at https://aistudio.google.com/app/apikey and add GEMINI_API_KEY=your_key to server/.env"
        }), 503

    try:
        file = request.files.get("file")
        user_question = request.form.get(
            "question",
            "What does this medical report indicate? Are the values normal? What precautions should I take?"
        )

        if not file:
            return jsonify({"success": False, "error": "No file provided"}), 400

        ext = os.path.splitext(file.filename)[1].lower()
        allowed = [".pdf", ".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"]
        if ext not in allowed:
            return jsonify({
                "success": False,
                "error": f"File type '{ext}' not supported. Please upload: PDF, JPG, PNG, or TIFF"
            }), 400

        if not file.filename:
            return jsonify({"success": False, "error": "Invalid filename"}), 400

        # Save to temp file
        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
            file.save(tmp.name)
            tmp_path = tmp.name

        try:
            report_text = extract_text_from_file(tmp_path, client)

            if not report_text or len(report_text.strip()) < 20:
                return jsonify({
                    "success": False,
                    "error": "Could not extract meaningful text from this file. Try uploading a text-based PDF."
                }), 422

            prompt = build_analysis_prompt(report_text, user_question)
            analysis = call_gemini(client, prompt)

            return jsonify({
                "success": True,
                "analysis": analysis,
                "filename": file.filename,
                "extracted_text_preview": report_text[:300] + "..." if len(report_text) > 300 else report_text
            }), 200

        finally:
            try:
                os.unlink(tmp_path)
            except Exception:
                pass

    except json.JSONDecodeError as e:
        return jsonify({"success": False, "error": f"AI response parsing error. Please try again: {e}"}), 500
    except Exception as e:
        traceback.print_exc()
        return jsonify({"success": False, "error": f"Analysis failed: {str(e)}"}), 500
