import os
import tempfile
import traceback
import json
import fitz  # PyMuPDF
from flask import request, jsonify
from config.db import db
import google.generativeai as genai

reports_collection = db["reports"]

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Models tried in order — if one quota/404, next is tried automatically
GEMINI_MODELS = [
    "gemini-1.5-flash",
    "gemini-1.5-flash-8b",
    "gemini-1.5-pro",
    "gemini-2.0-flash",
]

MEDICAL_DISCLAIMER = (
    "⚠️ IMPORTANT DISCLAIMER: This analysis is generated by an AI system and is "
    "intended for informational purposes ONLY. It is NOT a medical diagnosis and should "
    "NEVER replace professional medical advice, examination, or treatment. Always consult "
    "a qualified and licensed healthcare professional before making any medical decisions. "
    "In case of a medical emergency, contact emergency services immediately."
)


def get_model(model_name: str):
    """Configure and return a Gemini GenerativeModel."""
    if not GEMINI_API_KEY or GEMINI_API_KEY == "your_free_gemini_api_key_here":
        return None
    genai.configure(api_key=GEMINI_API_KEY)
    return genai.GenerativeModel(model_name)


def extract_text_from_pdf(filepath: str) -> str:
    """Extract text from a PDF file using PyMuPDF."""
    try:
        doc = fitz.open(filepath)
        text = ""
        for page in doc:
            text += page.get_text()
        doc.close()
        return text.strip()
    except Exception as e:
        return f"[PDF extraction error: {e}]"


def extract_text_from_image(filepath: str) -> str:
    """Extract text from an image using Gemini Vision."""
    try:
        import PIL.Image
        img = PIL.Image.open(filepath)

        prompt = (
            "Extract ALL text from this medical report image exactly as it appears, "
            "including all numbers, values, units, reference ranges, and labels. "
            "Do not interpret or summarize — just extract the raw text."
        )

        for model_name in GEMINI_MODELS:
            try:
                model = get_model(model_name)
                if not model:
                    return "[Gemini API key not configured]"
                response = model.generate_content([prompt, img])
                return response.text.strip()
            except Exception as e:
                err = str(e)
                if any(x in err for x in ["429", "RESOURCE_EXHAUSTED", "404", "NOT_FOUND", "quota"]):
                    continue
                raise

        return "[All Gemini models quota exhausted for image extraction]"
    except Exception as e:
        return f"[Image text extraction error: {e}]"


def extract_text_from_file(filepath: str) -> str:
    """Smart text extraction based on file type."""
    ext = os.path.splitext(filepath)[1].lower()

    if ext == ".pdf":
        text = extract_text_from_pdf(filepath)
        if len(text) < 50:
            return extract_text_from_image(filepath)
        return text

    elif ext in [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"]:
        return extract_text_from_image(filepath)

    else:
        try:
            with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                return f.read().strip()
        except Exception as e:
            return f"[File read error: {e}]"


def build_analysis_prompt(report_text: str, user_question: str) -> str:
    """Build the structured medical analysis prompt."""
    return f"""You are an expert medical AI assistant analyzing a patient's medical report.
Your analysis must be accurate, evidence-based, and cautious.
Base your response ONLY on the information present in the report.

MEDICAL REPORT CONTENT:
---
{report_text[:10000]}
---

PATIENT QUESTION: {user_question}

Analyze this report and respond in the following JSON format ONLY (no other text):
{{
  "summary": "Clear 2-3 sentence summary of what this report shows and its overall significance",
  "possible_conditions": [
    {{
      "condition": "Name of potential condition/finding",
      "evidence": "Specific data from the report that suggests this",
      "confidence": "High/Medium/Low"
    }}
  ],
  "key_findings": [
    "Key finding 1 from the report with specific values",
    "Key finding 2 from the report with specific values"
  ],
  "normal_values": [
    "Value that is within normal range"
  ],
  "precautions": [
    "Specific precaution or recommendation",
    "Lifestyle change recommendation"
  ],
  "urgency_level": "Routine OR Soon OR Urgent OR Emergency",
  "urgency_reason": "Brief explanation for the urgency level",
  "when_to_seek_immediate_help": [
    "Specific symptom or situation requiring immediate medical attention"
  ],
  "questions_for_doctor": [
    "Important question patient should ask their doctor"
  ],
  "disclaimer": "This AI analysis is for informational purposes only and does not constitute medical advice. Always consult a qualified healthcare professional."
}}

CRITICAL RULES:
1. Only mention conditions that have clear evidence in the report
2. If values are normal, say so explicitly
3. If something cannot be determined from the report, state "Cannot be determined from available information"
4. Always prefer caution over optimism in urgency assessment
5. Return ONLY valid JSON — no markdown, no extra text"""


def call_gemini(prompt: str) -> dict:
    """Call Gemini with automatic model fallback if quota/404 occurs."""
    if not GEMINI_API_KEY or GEMINI_API_KEY == "your_free_gemini_api_key_here":
        raise Exception(
            "Gemini API key not configured. Get your FREE key at "
            "https://aistudio.google.com/app/apikey and add GEMINI_API_KEY to Render environment."
        )

    genai.configure(api_key=GEMINI_API_KEY)
    last_error = None

    for model_name in GEMINI_MODELS:
        try:
            model = genai.GenerativeModel(
                model_name,
                generation_config=genai.types.GenerationConfig(
                    temperature=0.1,
                    max_output_tokens=3000,
                )
            )
            response = model.generate_content(prompt)
            raw = response.text.strip()

            # Remove markdown code fences if present
            if raw.startswith("```"):
                parts = raw.split("```")
                raw = parts[1] if len(parts) > 1 else raw
                if raw.startswith("json"):
                    raw = raw[4:]
            raw = raw.strip().rstrip("```").strip()

            return json.loads(raw)

        except Exception as e:
            err_str = str(e)
            if any(x in err_str for x in ["429", "RESOURCE_EXHAUSTED", "404", "NOT_FOUND", "quota"]):
                last_error = e
                continue   # try next model
            raise          # real error — surface it

    # All models exhausted
    raise Exception(
        "AI service temporarily unavailable — all model quotas exhausted. "
        "Please try again in a few minutes, or generate a new Gemini API key at "
        "https://aistudio.google.com/app/apikey (create in a NEW project)."
    )


def analyze_report():
    """Analyze an existing report by report_id or filepath."""
    if not GEMINI_API_KEY:
        return jsonify({
            "success": False,
            "error": "Gemini API key not configured."
        }), 503

    try:
        data = request.json or {}
        report_id = data.get("report_id")
        user_question = data.get(
            "question",
            "What does this medical report indicate? Are the values normal? What precautions should I take?"
        )
        filepath = data.get("filepath")

        if report_id and not filepath:
            from bson import ObjectId
            report = reports_collection.find_one({"_id": ObjectId(report_id)})
            if not report:
                return jsonify({"success": False, "error": "Report not found"}), 404
            filepath = report.get("filepath")

        if not filepath or not os.path.exists(filepath):
            return jsonify({
                "success": False,
                "error": "Report file not found on server. It may have been moved or deleted."
            }), 404

        report_text = extract_text_from_file(filepath)

        if not report_text or len(report_text.strip()) < 20:
            return jsonify({
                "success": False,
                "error": "Could not extract meaningful text from this report."
            }), 422

        prompt   = build_analysis_prompt(report_text, user_question)
        analysis = call_gemini(prompt)

        return jsonify({
            "success": True,
            "analysis": analysis,
            "extracted_text_preview": report_text[:300] + "..." if len(report_text) > 300 else report_text
        }), 200

    except json.JSONDecodeError as e:
        return jsonify({"success": False, "error": f"AI response parsing error: {e}"}), 500
    except Exception as e:
        traceback.print_exc()
        return jsonify({"success": False, "error": str(e)}), 500


def analyze_uploaded_report():
    """Analyze a freshly uploaded report file."""
    if not GEMINI_API_KEY:
        return jsonify({
            "success": False,
            "error": "Gemini API key not configured. Get your FREE key at https://aistudio.google.com/app/apikey"
        }), 503

    try:
        file          = request.files.get("file")
        user_question = request.form.get(
            "question",
            "What does this medical report indicate? Are the values normal? What precautions should I take?"
        )

        if not file:
            return jsonify({"success": False, "error": "No file provided"}), 400

        ext     = os.path.splitext(file.filename)[1].lower()
        allowed = [".pdf", ".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"]
        if ext not in allowed:
            return jsonify({
                "success": False,
                "error": f"File type '{ext}' not supported. Please upload: PDF, JPG, PNG, or TIFF"
            }), 400

        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
            file.save(tmp.name)
            tmp_path = tmp.name

        try:
            report_text = extract_text_from_file(tmp_path)

            if not report_text or len(report_text.strip()) < 20:
                return jsonify({
                    "success": False,
                    "error": "Could not extract meaningful text from this file. Try uploading a text-based PDF."
                }), 422

            prompt   = build_analysis_prompt(report_text, user_question)
            analysis = call_gemini(prompt)

            return jsonify({
                "success": True,
                "analysis": analysis,
                "filename": file.filename,
                "extracted_text_preview": report_text[:300] + "..." if len(report_text) > 300 else report_text
            }), 200

        finally:
            try:
                os.unlink(tmp_path)
            except Exception:
                pass

    except json.JSONDecodeError as e:
        return jsonify({"success": False, "error": f"AI response parsing error. Please try again."}), 500
    except Exception as e:
        traceback.print_exc()
        return jsonify({"success": False, "error": str(e)}), 500
