import os
import tempfile
import traceback
import json
import fitz  # PyMuPDF
from flask import request, jsonify
from config.db import db
import requests as http_requests

reports_collection = db["reports"]

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# Models tried in order — free tier, no quota issues
GROQ_MODELS = [
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
    "mixtral-8x7b-32768",
]

MEDICAL_DISCLAIMER = (
    "⚠️ IMPORTANT DISCLAIMER: This analysis is generated by an AI system and is "
    "intended for informational purposes ONLY. It is NOT a medical diagnosis and should "
    "NEVER replace professional medical advice, examination, or treatment. Always consult "
    "a qualified and licensed healthcare professional before making any medical decisions. "
    "In case of a medical emergency, contact emergency services immediately."
)


def extract_text_from_pdf(filepath: str) -> str:
    """Extract text from a PDF file using PyMuPDF."""
    try:
        doc = fitz.open(filepath)
        text = ""
        for page in doc:
            text += page.get_text()
        doc.close()
        return text.strip()
    except Exception as e:
        return f"[PDF extraction error: {e}]"


def extract_text_from_file(filepath: str) -> str:
    """Smart text extraction based on file type."""
    ext = os.path.splitext(filepath)[1].lower()

    if ext == ".pdf":
        return extract_text_from_pdf(filepath)

    elif ext in [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"]:
        return "[Image files: text extraction not supported without Vision API. Please upload a PDF.]"

    else:
        try:
            with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                return f.read().strip()
        except Exception as e:
            return f"[File read error: {e}]"


def build_analysis_prompt(report_text: str, user_question: str) -> str:
    """Build the structured medical analysis prompt."""
    return f"""You are an expert medical AI assistant analyzing a patient's medical report.
Your analysis must be accurate, evidence-based, and cautious.
Base your response ONLY on the information present in the report.

MEDICAL REPORT CONTENT:
---
{report_text[:10000]}
---

PATIENT QUESTION: {user_question}

Analyze this report and respond in the following JSON format ONLY (no other text, no markdown):
{{
  "summary": "Clear 2-3 sentence summary of what this report shows and its overall significance",
  "possible_conditions": [
    {{
      "condition": "Name of potential condition/finding",
      "evidence": "Specific data from the report that suggests this",
      "confidence": "High/Medium/Low"
    }}
  ],
  "key_findings": [
    "Key finding 1 from the report with specific values",
    "Key finding 2 from the report with specific values"
  ],
  "normal_values": [
    "Value that is within normal range"
  ],
  "precautions": [
    "Specific precaution or recommendation",
    "Lifestyle change recommendation"
  ],
  "urgency_level": "Routine OR Soon OR Urgent OR Emergency",
  "urgency_reason": "Brief explanation for the urgency level",
  "when_to_seek_immediate_help": [
    "Specific symptom or situation requiring immediate medical attention"
  ],
  "questions_for_doctor": [
    "Important question patient should ask their doctor"
  ],
  "disclaimer": "This AI analysis is for informational purposes only and does not constitute medical advice. Always consult a qualified healthcare professional."
}}

CRITICAL: Return ONLY valid JSON. No markdown, no code fences, no extra text."""


def call_groq(prompt: str) -> dict:
    """Call Groq API with automatic model fallback."""
    if not GROQ_API_KEY:
        raise Exception(
            "Groq API key not configured. Get your FREE key at "
            "https://console.groq.com — sign up, go to API Keys, create a key. "
            "Then add GROQ_API_KEY to Render environment variables."
        )

    last_error = None

    for model in GROQ_MODELS:
        try:
            resp = http_requests.post(
                GROQ_API_URL,
                headers={
                    "Authorization": f"Bearer {GROQ_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": model,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.1,
                    "max_tokens": 3000,
                },
                timeout=60,
            )

            if resp.status_code == 429:
                last_error = Exception(f"Rate limited on {model}")
                continue  # try next model

            if resp.status_code != 200:
                last_error = Exception(f"Groq API error {resp.status_code}: {resp.text}")
                continue

            raw = resp.json()["choices"][0]["message"]["content"].strip()

            # Remove markdown code fences if present
            if raw.startswith("```"):
                parts = raw.split("```")
                raw = parts[1] if len(parts) > 1 else raw
                if raw.startswith("json"):
                    raw = raw[4:]
            raw = raw.strip().rstrip("```").strip()

            return json.loads(raw)

        except json.JSONDecodeError as e:
            raise Exception(f"AI response parsing error — please try again: {e}")
        except Exception as e:
            err_str = str(e)
            if "429" in err_str or "rate" in err_str.lower():
                last_error = e
                continue
            raise

    raise Exception(
        "All Groq models temporarily rate-limited. Please wait 1 minute and try again."
    )


def analyze_report():
    """Analyze an existing report by report_id or filepath."""
    if not GROQ_API_KEY:
        return jsonify({"success": False, "error": "Groq API key not configured."}), 503

    try:
        data          = request.json or {}
        report_id     = data.get("report_id")
        user_question = data.get("question", "What does this medical report indicate? Are the values normal? What precautions should I take?")
        filepath      = data.get("filepath")

        if report_id and not filepath:
            from bson import ObjectId
            report = reports_collection.find_one({"_id": ObjectId(report_id)})
            if not report:
                return jsonify({"success": False, "error": "Report not found"}), 404
            filepath = report.get("filepath")

        if not filepath or not os.path.exists(filepath):
            return jsonify({"success": False, "error": "Report file not found on server."}), 404

        report_text = extract_text_from_file(filepath)

        if not report_text or len(report_text.strip()) < 20:
            return jsonify({"success": False, "error": "Could not extract text from this report."}), 422

        analysis = call_groq(build_analysis_prompt(report_text, user_question))

        return jsonify({
            "success": True,
            "analysis": analysis,
            "extracted_text_preview": report_text[:300] + "..." if len(report_text) > 300 else report_text
        }), 200

    except Exception as e:
        traceback.print_exc()
        return jsonify({"success": False, "error": str(e)}), 500


def analyze_uploaded_report():
    """Analyze a freshly uploaded report file."""
    if not GROQ_API_KEY:
        return jsonify({"success": False, "error": "Groq API key not configured. Get it free at https://console.groq.com"}), 503

    try:
        file          = request.files.get("file")
        user_question = request.form.get("question", "What does this medical report indicate? Are the values normal? What precautions should I take?")

        if not file:
            return jsonify({"success": False, "error": "No file provided"}), 400

        ext     = os.path.splitext(file.filename)[1].lower()
        allowed = [".pdf", ".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif"]
        if ext not in allowed:
            return jsonify({"success": False, "error": f"File type '{ext}' not supported. Please upload a PDF."}), 400

        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
            file.save(tmp.name)
            tmp_path = tmp.name

        try:
            report_text = extract_text_from_file(tmp_path)

            if not report_text or len(report_text.strip()) < 20:
                return jsonify({"success": False, "error": "Could not extract text from this file. Try a text-based PDF."}), 422

            analysis = call_groq(build_analysis_prompt(report_text, user_question))

            return jsonify({
                "success": True,
                "analysis": analysis,
                "filename": file.filename,
                "extracted_text_preview": report_text[:300] + "..." if len(report_text) > 300 else report_text
            }), 200

        finally:
            try:
                os.unlink(tmp_path)
            except Exception:
                pass

    except Exception as e:
        traceback.print_exc()
        return jsonify({"success": False, "error": str(e)}), 500
